/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportIssueRouteImport } from './routes/report-issue'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocreadyRouteImport } from './routes/docready'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComplaintsRouteImport } from './routes/complaints'
import { Route as AiSaathiRouteImport } from './routes/ai-saathi'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpportunitiesIdRouteImport } from './routes/opportunities.$id'
import { Route as MissionsIdRouteImport } from './routes/missions.$id'
import { Route as ComplaintsIdRouteImport } from './routes/complaints.$id'

const ReportIssueRoute = ReportIssueRouteImport.update({
  id: '/report-issue',
  path: '/report-issue',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocreadyRoute = DocreadyRouteImport.update({
  id: '/docready',
  path: '/docready',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsRoute = ComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSaathiRoute = AiSaathiRouteImport.update({
  id: '/ai-saathi',
  path: '/ai-saathi',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIdRoute = OpportunitiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OpportunitiesRoute,
} as any)
const MissionsIdRoute = MissionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MissionsRoute,
} as any)
const ComplaintsIdRoute = ComplaintsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ComplaintsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-saathi': typeof AiSaathiRoute
  '/complaints': typeof ComplaintsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/docready': typeof DocreadyRoute
  '/login': typeof LoginRoute
  '/missions': typeof MissionsRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/report-issue': typeof ReportIssueRoute
  '/complaints/$id': typeof ComplaintsIdRoute
  '/missions/$id': typeof MissionsIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-saathi': typeof AiSaathiRoute
  '/complaints': typeof ComplaintsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/docready': typeof DocreadyRoute
  '/login': typeof LoginRoute
  '/missions': typeof MissionsRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/report-issue': typeof ReportIssueRoute
  '/complaints/$id': typeof ComplaintsIdRoute
  '/missions/$id': typeof MissionsIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-saathi': typeof AiSaathiRoute
  '/complaints': typeof ComplaintsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/docready': typeof DocreadyRoute
  '/login': typeof LoginRoute
  '/missions': typeof MissionsRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/report-issue': typeof ReportIssueRoute
  '/complaints/$id': typeof ComplaintsIdRoute
  '/missions/$id': typeof MissionsIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-saathi'
    | '/complaints'
    | '/dashboard'
    | '/docready'
    | '/login'
    | '/missions'
    | '/onboarding'
    | '/opportunities'
    | '/profile'
    | '/register'
    | '/report-issue'
    | '/complaints/$id'
    | '/missions/$id'
    | '/opportunities/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-saathi'
    | '/complaints'
    | '/dashboard'
    | '/docready'
    | '/login'
    | '/missions'
    | '/onboarding'
    | '/opportunities'
    | '/profile'
    | '/register'
    | '/report-issue'
    | '/complaints/$id'
    | '/missions/$id'
    | '/opportunities/$id'
  id:
    | '__root__'
    | '/'
    | '/ai-saathi'
    | '/complaints'
    | '/dashboard'
    | '/docready'
    | '/login'
    | '/missions'
    | '/onboarding'
    | '/opportunities'
    | '/profile'
    | '/register'
    | '/report-issue'
    | '/complaints/$id'
    | '/missions/$id'
    | '/opportunities/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiSaathiRoute: typeof AiSaathiRoute
  ComplaintsRoute: typeof ComplaintsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DocreadyRoute: typeof DocreadyRoute
  LoginRoute: typeof LoginRoute
  MissionsRoute: typeof MissionsRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  OpportunitiesRoute: typeof OpportunitiesRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ReportIssueRoute: typeof ReportIssueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/report-issue': {
      id: '/report-issue'
      path: '/report-issue'
      fullPath: '/report-issue'
      preLoaderRoute: typeof ReportIssueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docready': {
      id: '/docready'
      path: '/docready'
      fullPath: '/docready'
      preLoaderRoute: typeof DocreadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints': {
      id: '/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof ComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-saathi': {
      id: '/ai-saathi'
      path: '/ai-saathi'
      fullPath: '/ai-saathi'
      preLoaderRoute: typeof AiSaathiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$id': {
      id: '/opportunities/$id'
      path: '/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof OpportunitiesIdRouteImport
      parentRoute: typeof OpportunitiesRoute
    }
    '/missions/$id': {
      id: '/missions/$id'
      path: '/$id'
      fullPath: '/missions/$id'
      preLoaderRoute: typeof MissionsIdRouteImport
      parentRoute: typeof MissionsRoute
    }
    '/complaints/$id': {
      id: '/complaints/$id'
      path: '/$id'
      fullPath: '/complaints/$id'
      preLoaderRoute: typeof ComplaintsIdRouteImport
      parentRoute: typeof ComplaintsRoute
    }
  }
}

interface ComplaintsRouteChildren {
  ComplaintsIdRoute: typeof ComplaintsIdRoute
}

const ComplaintsRouteChildren: ComplaintsRouteChildren = {
  ComplaintsIdRoute: ComplaintsIdRoute,
}

const ComplaintsRouteWithChildren = ComplaintsRoute._addFileChildren(
  ComplaintsRouteChildren,
)

interface MissionsRouteChildren {
  MissionsIdRoute: typeof MissionsIdRoute
}

const MissionsRouteChildren: MissionsRouteChildren = {
  MissionsIdRoute: MissionsIdRoute,
}

const MissionsRouteWithChildren = MissionsRoute._addFileChildren(
  MissionsRouteChildren,
)

interface OpportunitiesRouteChildren {
  OpportunitiesIdRoute: typeof OpportunitiesIdRoute
}

const OpportunitiesRouteChildren: OpportunitiesRouteChildren = {
  OpportunitiesIdRoute: OpportunitiesIdRoute,
}

const OpportunitiesRouteWithChildren = OpportunitiesRoute._addFileChildren(
  OpportunitiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiSaathiRoute: AiSaathiRoute,
  ComplaintsRoute: ComplaintsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DocreadyRoute: DocreadyRoute,
  LoginRoute: LoginRoute,
  MissionsRoute: MissionsRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  OpportunitiesRoute: OpportunitiesRouteWithChildren,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ReportIssueRoute: ReportIssueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
