/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportIssueRouteImport } from './routes/report-issue'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocreadyRouteImport } from './routes/docready'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AiSaathiRouteImport } from './routes/ai-saathi'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpportunitiesIndexRouteImport } from './routes/opportunities.index'
import { Route as MissionsIndexRouteImport } from './routes/missions.index'
import { Route as ComplaintsIndexRouteImport } from './routes/complaints.index'
import { Route as OpportunitiesIdRouteImport } from './routes/opportunities.$id'
import { Route as MissionsIdRouteImport } from './routes/missions.$id'
import { Route as ComplaintsIdRouteImport } from './routes/complaints.$id'

const ReportIssueRoute = ReportIssueRouteImport.update({
  id: '/report-issue',
  path: '/report-issue',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocreadyRoute = DocreadyRouteImport.update({
  id: '/docready',
  path: '/docready',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSaathiRoute = AiSaathiRouteImport.update({
  id: '/ai-saathi',
  path: '/ai-saathi',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIndexRoute = OpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsIndexRoute = MissionsIndexRouteImport.update({
  id: '/missions/',
  path: '/missions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsIndexRoute = ComplaintsIndexRouteImport.update({
  id: '/complaints/',
  path: '/complaints/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIdRoute = OpportunitiesIdRouteImport.update({
  id: '/opportunities/$id',
  path: '/opportunities/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsIdRoute = MissionsIdRouteImport.update({
  id: '/missions/$id',
  path: '/missions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsIdRoute = ComplaintsIdRouteImport.update({
  id: '/complaints/$id',
  path: '/complaints/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-saathi': typeof AiSaathiRoute
  '/dashboard': typeof DashboardRoute
  '/docready': typeof DocreadyRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/report-issue': typeof ReportIssueRoute
  '/complaints/$id': typeof ComplaintsIdRoute
  '/missions/$id': typeof MissionsIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/complaints/': typeof ComplaintsIndexRoute
  '/missions/': typeof MissionsIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-saathi': typeof AiSaathiRoute
  '/dashboard': typeof DashboardRoute
  '/docready': typeof DocreadyRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/report-issue': typeof ReportIssueRoute
  '/complaints/$id': typeof ComplaintsIdRoute
  '/missions/$id': typeof MissionsIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/complaints': typeof ComplaintsIndexRoute
  '/missions': typeof MissionsIndexRoute
  '/opportunities': typeof OpportunitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-saathi': typeof AiSaathiRoute
  '/dashboard': typeof DashboardRoute
  '/docready': typeof DocreadyRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/report-issue': typeof ReportIssueRoute
  '/complaints/$id': typeof ComplaintsIdRoute
  '/missions/$id': typeof MissionsIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/complaints/': typeof ComplaintsIndexRoute
  '/missions/': typeof MissionsIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-saathi'
    | '/dashboard'
    | '/docready'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/report-issue'
    | '/complaints/$id'
    | '/missions/$id'
    | '/opportunities/$id'
    | '/complaints/'
    | '/missions/'
    | '/opportunities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-saathi'
    | '/dashboard'
    | '/docready'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/report-issue'
    | '/complaints/$id'
    | '/missions/$id'
    | '/opportunities/$id'
    | '/complaints'
    | '/missions'
    | '/opportunities'
  id:
    | '__root__'
    | '/'
    | '/ai-saathi'
    | '/dashboard'
    | '/docready'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/report-issue'
    | '/complaints/$id'
    | '/missions/$id'
    | '/opportunities/$id'
    | '/complaints/'
    | '/missions/'
    | '/opportunities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiSaathiRoute: typeof AiSaathiRoute
  DashboardRoute: typeof DashboardRoute
  DocreadyRoute: typeof DocreadyRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ReportIssueRoute: typeof ReportIssueRoute
  ComplaintsIdRoute: typeof ComplaintsIdRoute
  MissionsIdRoute: typeof MissionsIdRoute
  OpportunitiesIdRoute: typeof OpportunitiesIdRoute
  ComplaintsIndexRoute: typeof ComplaintsIndexRoute
  MissionsIndexRoute: typeof MissionsIndexRoute
  OpportunitiesIndexRoute: typeof OpportunitiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/report-issue': {
      id: '/report-issue'
      path: '/report-issue'
      fullPath: '/report-issue'
      preLoaderRoute: typeof ReportIssueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docready': {
      id: '/docready'
      path: '/docready'
      fullPath: '/docready'
      preLoaderRoute: typeof DocreadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-saathi': {
      id: '/ai-saathi'
      path: '/ai-saathi'
      fullPath: '/ai-saathi'
      preLoaderRoute: typeof AiSaathiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/': {
      id: '/opportunities/'
      path: '/opportunities'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof OpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions/': {
      id: '/missions/'
      path: '/missions'
      fullPath: '/missions/'
      preLoaderRoute: typeof MissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints/': {
      id: '/complaints/'
      path: '/complaints'
      fullPath: '/complaints/'
      preLoaderRoute: typeof ComplaintsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$id': {
      id: '/opportunities/$id'
      path: '/opportunities/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof OpportunitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions/$id': {
      id: '/missions/$id'
      path: '/missions/$id'
      fullPath: '/missions/$id'
      preLoaderRoute: typeof MissionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints/$id': {
      id: '/complaints/$id'
      path: '/complaints/$id'
      fullPath: '/complaints/$id'
      preLoaderRoute: typeof ComplaintsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiSaathiRoute: AiSaathiRoute,
  DashboardRoute: DashboardRoute,
  DocreadyRoute: DocreadyRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ReportIssueRoute: ReportIssueRoute,
  ComplaintsIdRoute: ComplaintsIdRoute,
  MissionsIdRoute: MissionsIdRoute,
  OpportunitiesIdRoute: OpportunitiesIdRoute,
  ComplaintsIndexRoute: ComplaintsIndexRoute,
  MissionsIndexRoute: MissionsIndexRoute,
  OpportunitiesIndexRoute: OpportunitiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
